name: first github action

on:
  push:
    branches: [ master ]
    workflow_dispatch:

jobs:
  print hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello-World"

